### PR TITLE
Improved listing for potential users and changed the initial selectio…

### PR DESCRIPTION
**Pull request by Kathrin84**
…n to All users by default.

### CODE REVIEW

**Comment by abias** [comment]
Hey @chadmazilly, could you please consider to have a look at this pull request finally?

Thanks,
Alex

**Comment by chadmazilly** [comment]
Hey @abias, I will take a look at this pull request next week for sure. Looks like it would be a good improvement and is simple enough. Will comment back here on the status. Thanks!

**Comment by abias** [comment]
Hey @chadmazilly, do you have any news about this pull request?

**Comment by chadmazilly** [comment]
Hey there @abias, I can certainly test it and pull it in this week and report back here.

**Comment by chadmazilly** [comment]
@abias I just tested this out and, while it does push the "All Users" option to the top of the multi-select on the email form (and selects it), it does not actually select all users in the multi-select below. Is that the type of behavior that you're looking for?

I tested this is a system with 100 users: 100 students, and 3 groups each with 10 unique student users. Like I said, I do see that "All Users" option at the top but it does not select them. Am I missing something here?

Sounds like this needs to be address of the JS side as well, but I haven't explored that yet. I'll keep this open for your comments and suggestions.

**Comment by rrusso** [comment]
This is stale and is not relevant in the latest Quickmail.

**Pull request closed without merging**
