### PR TITLE
First steps in performance and code improvements

### PR DESCRIPTION
**Pull request by agrowe**
After some discussions with @elliott2081 on #164 we thought it would be better to start a new PR based off the Dev branch and only pull in or work on one feature at a time.

In this Pull Request it is some of the simpler tasks.
- The name field in the config table has been raised to char(50) to eventually allow longer config settings
- Multiple duplicate calls in the form definition have been removed and replaced with $this-> calls.
- The is_numeric() duplicates in the forms option_value() function have been removed and made into a single function call.

Let me know what you think and we can start working on the "experimental settings" and the main changes to the SQL.

Thanks
Alex

### CODE REVIEW

**Comment by elliott2081** [comment]
Hello again, I will be looking at this soon, testing these four in a row looks like it should be pretty straight forward. Thanks

**Comment by elliott2081** [comment]
Hello agrowe. do you have an email?

**Comment by agrowe** [comment]
I have just added it to my GitHub profile

**Comment by chadmazilly** [comment]
Closing this as we'll only be focused on bug/compatibility fixes for this original version of Quickmail. A new Quickmail v2 is available for new features and PRs (currently on the `dev-34` branch if you're interested).

**Pull request closed without merging**
