### PR TITLE
Added support for also emailing guardians

### PR DESCRIPTION
**Pull request by johnpanos**
My school wanted to be able to have the option to also email guardians whenever students got an email. I implemented that by having it be optional during the setup process, and while composing an email.

### CODE REVIEW

**Comment by vcs-edtech** [comment]
Hi Chad, any updates on this? We'd love to start using this guardian feature next week... it's a great feature that I think a lot of K-12 schools would love to have. Thanks!

**Comment by johnpanos** [comment]
@chadmazilly Any updates?

**Comment by chadmazilly** [comment]
Hello all, wanted to weigh in on this. @johnpanos and I just had some offline discussion and I wanted to get some thoughts.

Is there a Moodle standard way of assigning mentors to a user? Seems like this PR assumes it is done if a specific way.

**Comment by vcs-edtech** [comment]
There’s no standard way of assigning mentors/guardians/parents in Moodle… organizations can choose to create custom role to fit their needs (https://docs.moodle.org/35/en/Parent_role), or, they can use a plugin.

What we’re trying to do here is new… it’s use an optional field that can contain any data and pull from that to send emails to multiple email  addresses in a user’s profile… it could just be an additional email for the student, but in our case, we need to use it to also send to students’ guardians.

Jeremy Cunningham, M.Ed
Education Technology Coordinator
VCS.net<http://vcs.net/> | @vcschools<http://twitter.com/vcschools> | @vcs_edtech<https://twitter.com/vcs_edtech>
408.513.2594
[VCS_logo_1C]

**Comment by rrusso** [comment]
We'll implement a configurable method of doing this where the admin can select the additional profile field(s) that the university can use to input parent / mentor email addresses and a method for senders to select from those. This way no one is stuck to one method of implementing this and it will work for multiple use-cases. 

The job Chad has done with the new Quickmail is nothing short of astonishing and I look forward to the final release.

**Comment by vcs-edtech** [comment]
Awesome, that sounds great!

Please let us know when we can update the plugin… we’re hosted by Remote-Learner and they’ll need to update it on their end before they can push it to us!

Jeremy Cunningham, M.Ed
Education Technology Coordinator
VCS.net<http://vcs.net/> | @vcschools<http://twitter.com/vcschools> | @vcs_edtech<https://twitter.com/vcs_edtech>
408.513.2594
[VCS_logo_1C]

**Pull request closed without merging**
